apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: tiulanches
          image: tiulanchesacr.azurecr.io/tiulanches:latest  
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1.0"                  
          ports:
            - containerPort: 8080
              name: app-port
          env:
            - name: DATASOURCE_URL   
              valueFrom :
                configMapKeyRef:
                  name: app-config
                  key: ds_url
            - name: DATASOURCE_PASSWORD  
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ds_pass
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ds_username
            - name: ACCESS_TOKEN_MP
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mp_token
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: app-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: app-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app: app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
