apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiulanches-deployment
  labels:
    app: tiulanches-deployment
spec:
  selector:
    matchLabels:
      app: tiulanches
  replicas: 1
  template:
    metadata:
      labels:
        app: tiulanches
    spec:
      containers:
        - name: tiulanches
          image: tiulanchesacr.azurecr.io/tiulanches:latest  
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1.0"                  
          ports:
            - containerPort: 8080
              name: tiulanches-port
          env:
            - name: DATASOURCE_URL   
              valueFrom :
                configMapKeyRef:
                  name: tiulanches-config
                  key: ds_url
            - name: DATASOURCE_PASSWORD  
              valueFrom:
                configMapKeyRef:
                  name: tiulanches-config
                  key: ds_pass
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: tiulanches-config
                  key: ds_username
            - name: CONEXAO_KAFKA
              valueFrom :
                configMapKeyRef :
                  name : tiulanches-config
                  key : conexao_kafka                  
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: tiulanches-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: tiulanches-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: tiulanches-svc
spec:
  selector:
    app: tiulanches
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
