services:
  db:
    container_name: base-mysql
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456      
      - MYSQL_DATABASE=tiulanches
      - MYSQL_USER=adm
      - MYSQL_PASSWORD=adm123  
    ports:
      - 3306:3306
volumes:
  db_data: