apiVersion: v1                                                                                
kind: PersistentVolume                                                                        
metadata:                                                                                     
  name: mysql-pv
  labels:
    name: mysql-pv
spec:                                                                                         
  capacity:                                                                                   
    storage: 1Gi
  accessModes:                                                                                
    - ReadWriteOnce
  storageClassName: local-storage-db  
  persistentVolumeReclaimPolicy: Retain     
  hostPath:                                                                                   
    path: /var/lib/mysql
---                                                                                           
apiVersion: v1                                                                                
kind: PersistentVolumeClaim                                                                   
metadata:                                                                                     
  name: mysql-pvc                                                                        
  labels:
    name: mysql-pvc
spec:                                                                                         
  accessModes:                                                                                
    - ReadWriteOnce                                                                           
  resources:                                                                                  
    requests:                                                                                 
      storage: 1Gi
  storageClassName: local-storage-db
---	  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-mysql
  labels:
    app: base-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc
      containers:
      - name: mysql
        image: mysql:8.0
        envFrom:
        - configMapRef:
            name: db-config
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306  
      nodePort: 31100
