apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: db-config
data:
  MYSQL_ROOT_PASSWORD: 123abc
  DATASOURCE_PASSWORD: 123abc
  DATASOURCE_URL: jdbc:mysql://mysql:3306/tiulanches
  DATASOURCE_USERNAME: root
  