CREATE TABLE PRODUTOS(
	ID_PRODUTO bigint(20) NOT NULL AUTO_INCREMENT,
	CATEGORIA tinyint NOT NULL,
	NOME varchar(30) NOT NULL,
	DESCRICAO varchar(200) NOT NULL,
	PRECO decimal(4,2) NOT NULL,
	TEMPO_PREPARO tinyint DEFAULT 0,
	IMAGEM varchar(400) DEFAULT NULL,
	PRIMARY KEY (ID_PRODUTO)
);