CREATE TABLE PEDIDOS(
	ID_PEDIDO bigint(20) NOT NULL AUTO_INCREMENT,
	CPF varchar(11) NOT NULL,	
	STATUS tinyint NOT NULL DEFAULT 0,
	QRCODE varchar(400) NOT NULL,
	PAGO tinyint NOT NULL DEFAULT 0,	
	PRIMARY KEY (ID_PEDIDO)
);

ALTER TABLE PEDIDOS ADD CONSTRAINT fk_pedido_cliente FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);