CREATE TABLE ITENS_PEDIDOS(
	ID_PEDIDO bigint(20) NOT NULL,
	ID_PRODUTO bigint(20) NOT NULL,	
	QUANTIDADE tinyint NOT NULL DEFAULT 0,
	OBSERVACAO varchar(100),	
	PRIMARY KEY (ID_PEDIDO, ID_PRODUTO)
);

ALTER TABLE ITENS_PEDIDOS ADD CONSTRAINT fk_item_pedido_pedido FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO);
ALTER TABLE ITENS_PEDIDOS ADD CONSTRAINT fk_item_pedido_produto FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO);