name: Check app Tiu Lanches

on:
  pull_request:
    branches: [main]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 21
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Tests
      run: mvn test  

  sonar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1      
    - name: Set up JDK 21
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '21'
        distribution: 'temurin'        
    - name: SonarCloud Scan
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=luisferrarezi_tiulanches -Dsonar.organization=luisferrarezi -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 21
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean package
          
