name: Check app Tiu Lanches

on:
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 21
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean package

  docker-image:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.1.0
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
