name: Check app Tiu Lanches

on:
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 21
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean package

    - name: Azure Login
      uses: Azure/login@v2.0.0
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    - name: ACR Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.USERNAME_ACR }}
        password: ${{ secrets.PASSWORD_ID }}
        login-server: ${{ secrets.SERVER_ACR }}
    - run: |
        docker build . -t tiulanches.azurecr.io/tiulanches:latest
        docker push tiulanches.azurecr.io/tiulanches:latest
        
#  image-azure:
#    needs: build
#    runs-on: ubuntu-latest   
        
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v4.1.1
